AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloudformation template to create codepipeline for ECS deployment on EC2

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Instance type for EC2 instances
  ClusterSize:
    Type: Number
    Default: 2
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  VpcId:
    Type: AWS::EC2::VPC::Id
  IsELBNeeded:
    Type: String
    AllowedValues:
      - Y
      - N
  LoadBalancerPort:
    Type: Number
  HostPort:
    Type: Number
  ContainerPort:
    Type: Number
  HealthCheckPath:
    Type: String
  ListenerRulePriority:
    Type: Number
  PathPattern:
    Type: String
  ECSRole:
    Type: String
  TaskExecutionRole:
    Type: String

Conditions:
  ELBCondition: !Equals [ !Ref IsELBNeeded, Y ]

Resources:
  # ELB Creation
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Condition: ELBCondition
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: ELBCondition
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref LoadBalancerPort
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref HostPort
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: "instance"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 120
      Matcher:
        HttpCode: 200-299
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: !Ref ListenerRulePriority
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref PathPatern
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
  #ECS Cluster
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-ce1c36ab
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Sub arn:aws:iam:${AWS::Region}:${AWS::AccountId}:instance-profile/${ECSRole}
      SecurityGroups: !Ref SecurityGroup
    UserData:
      "Fn::Base64": !Sub |
          #!/bin/bash
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource LaunchConfiguration
          /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource AutoScalingGroup
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            add_instance_to_cluster:
              command: !Sub echo ECS_CLUSTER=${Cluster} > /etc/ecs/ecs.config
          files:
            "/etc/cfn/cfn-hup.conf":
              mode: 000400
              owner: root
              group: root
              content: !Sub |
                  [main]
                  stack=${AWS::StackId}
                  region=${AWS::Region}
            "/etc/cfn/hook.d/cfn-auto-reloader.conf":
              mode: 000400
              owner: root
              group: root
              content: !Sub |
                  [cfn-auto-reloader-hook]
                  triggers=post.update
                  path=Resources.ContainerInstances.Metadata.AWS::CloudFormation::Init
                  action=/opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource LaunchConfiguration
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: !Ref ClusterSize
      MaxSize: !Ref ClusterSize
      DesiredCapacity: !Ref ClusterSize
      CreationPolicy:
        ResourceSignal:
          Timeout: PT15M
      UpdatePolicy:
        AutoScalingRollingUpdate:
          MinInstanceInService: 1
          MaxBatchSize: 1
          PauseTime: PT15M
          WaitOnResourceSignal: true
      Tags:
        - Keys: Name
          Value: !Sub ${AWS::StackName}-EC2
          PropogateAtLaunch: true
  #ECS Service
  TaskDefition:
    Type: AWS::ECS::TaskDefition
    Properties:
      Family: !Sub ${AWS::StackName}-td
      RequiresCompatibilities: EC2
      Memory: 512
      Cpu: 256
      NetworkMode: bridge
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: ${AWS::StackName}-cd
          Image: amazon/amazon-ecs-example
          EntryPoint:
            - /usr/sbin/apach2
            - -D
            - FOREGROUND
          Essential: true
          Memory: 256
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Ref AWS::StackName
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/ecs/${AWS::StackName}
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      TaskDefition: !Ref TaskDefition
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: !Sub ${AWS::StackName}-lb
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup 
  #Code Pipeline
  CodeBuildDocker:
    Type: AWS::CodeBuild::Project
    Name: !Sub ${AWS::StackName}-docker
    ServiceRole: !Ref CodeBuildServiceRole
    VpcConfig:
      VpcId: !Ref VPC
      Subnets: !Ref Subnet
      SecurityGroupIds: !Ref SecurityGroup
    Environment:
      ComputeType: BUILD_GENERAL1_SMALL
      Image: aws/codebuild/docker:latest
      PrivilegedMode: true
      Type: LINUX_CONTAINER
      EnvironmentVariables:
        - Name: AWS_DEFAULT_REGION
          Value: !Ref AWS::Region
        - Name: REPOSITORY_URI
          Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}
        - Name: APPNAME
          Value: !Ref AWS::StackName
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email)
                - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
                - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
            build:
              commands:
                - docker build --tage "$IMAGE_URI" .
                - docker push "$IMAGE_URI"
                - echo "[{\"name\": \"$APPNAME\", \"imageUri\": $IMAGE_URI}]" > images.json
            artifacts:
              files: images.json
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Ref CodepipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: !Ref CodepipeArtifactLocation
      Stages:
        - Name: Source
          Actions:
            - Name: App
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: Source
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildDockerImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildDocker
              InputArtifacts:
                - Name: Source
                - Name: SourceBuild
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provder: ECS
              Configuration:
                ClusterName: !Ref Cluster
                ServiceName: !Ref Service
                FileName: images.json
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
